### ISSUE TITLE
Current Stable version ? 

### ISSUE THREAD

**Issue by jorisx** [siwapp/siwapp-sf1#4]
Hi
Where can i see the version of swipe-sf1?
I've been using Siwapp for some time, but what is the current stable version ?
We are using 0.4.1 which i once downloaded from http://www.siwapp.org, Is this still the stable and most recent release ? 

Thanks, 
Joris

**Comment by carlosescri** [comment]
Hi Joris,

The latest version is 0.4.1 but I've uploaded a 0.4.2 version to this github repository with the CSV export feature.

You will find it at: <https://github.com/siwapp/siwapp-sf1/releases>

In any case, the PHP version is almost abandoned. We are working in a completely revamped version made in Ruby on Rails.

**Comment by jorisx** [comment]
Nice, 

Is there any timeframe available for the update to the RoR version ? 
And do i need to have version  0.4.2  installed to update to the new RoR version of SiWAPP ?


Thanx for developing SiWapp its a great application, 
I really appreciate it and let me know if i can help in anything with graphics or visuals



Met vriendelijke groeten /  With warm regards,
© Joris.Sewandono.com <http://joris.sewandono.com/> // Interaction Designer 
® ReloadMedia.com <http://www.reloadmedia.com/> // Online Web/Application Design & Development

**Comment by carlosescri** [comment]
Thank you!

We use siwapp to learn new things so it's a slow development. As we add existing or new features to the RoR version, we update a migration script so there should be easy to switch.

Any help is welcome, if you have any ideas you want to share or you'd like to see implemented you can create a new issue and we will take it into account.
